### ISSUE TITLE
Install on Home Assistant OS

### ISSUE THREAD

**Issue by SebastianOlthuis** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#16]
I wanted to install this on Home Assistant OS because i didint wanna reinstall. My issue i had was when the add-on was running, I can't start the Docker container on port 3333 because it says the port is already in use on the host.

![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/e86ee198-47cc-4c68-9467-12e709cbcf94)

Conversely, if I stoped the add-on, I can start the Docker container just fine. However, if I then try to start the add-on, I encounterd the same problem.

![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/3c071155-9bf1-46d4-8def-f455ca5733b8)

To address this, I uninstalled the docker container and installed it with a changed port like this:

```
docker create \
  --restart unless-stopped \
  --env ML_API_TOKEN=obico_api_secret \
  --publish 3333:3332 \
  --name ha_bambu_lab_p1_spaghetti_detection \
  nberk/ha_bambu_lab_p1_spaghetti_detection_standalone:latest
docker create \
  --restart unless-stopped \
  --env ML_API_TOKEN=obico_api_secret \
  --publish 3333:3332 \
  --name ha_bambu_lab_p1_spaghetti_detection \
  nberk/ha_bambu_lab_p1_spaghetti_detection_standalone:latest
```
![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/e96fc5c8-098b-47ad-8896-b3b8ee2dfdac)

By using SSH into Home Assistant OS, I was able to install it without a typical Docker installation. Hopefully, this helps someone facing a similar issue saw a few posts online when first looking into this.

**Comment by SebastianOlthuis** [comment]
never mind idk why but it didnt give me a error the automation even said it was used 2-3 sec ago constandly but after few min this again 
![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/d98f7c7b-0485-418b-8c74-bef02c660145)

**Comment by nberktumer** [comment]
I think something else is using 3333 port in your server. So, despite of the unknown service error, your `--publish 3333:3332` argument is still wrong. 

The publish argument values are in `--publish <host_port>:<container_port>` format. So, it should be `--publish 3332:3333` instead. 
The ML detection backend should run in 3333 port in the docker container but it should bind to 3332 in your host server.

**Comment by SebastianOlthuis** [comment]
> I think something else is using 3333 port in your server. So, despite of the unknown service error, your `--publish 3333:3332` argument is still wrong.
> 
> The publish argument values are in `--publish <host_port>:<container_port>` format. So, it should be `--publish 3332:3333` instead. The ML detection backend should run in 3333 port in the docker container but it should bind to 3332 in your host server.

thanks for the fast reply. saldy it didnt fix it 
![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/83f6a9d9-169f-4594-a3bd-035dd614342d)

![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/43ab3a82-bf2d-4bd1-a12e-ad32bece9136)

**Comment by SebastianOlthuis** [comment]
Maybe this is stupid but could this be the issue ?  because thats not even same subnet as my network

![ip](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/89dc2aa4-2b95-421e-afa8-44d003f8c4e9)

**Comment by nberktumer** [comment]
You should use 3332 port in `Obico ML API Host` config. The ML API runs with 3333 port within the docker container, but everything else outside the container can access the ML API via 3332 port since you bind it to 3332 port using `--publish 3332:3333` argument.

**Comment by SebastianOlthuis** [comment]
> You should use 3332 port in `Obico ML API Host` config. The ML API runs with 3333 port within the docker container, but everything else outside the container can access the ML API via 3332 port since you bind it to 3332 port using `--publish 3332:3333` argument.

i tried this already after you last reply because i wanted to make sure im not mixing something up so i tried both 3332 and 3333 in the config. by config i mean the automatison from your blueprint.

![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/52d8f62a-4e21-432d-88fd-80c67a1ec6d3)

in the config from the addon i cant use 3333 so im on 3332 because otherwise ill get the already use by host error again.

**Comment by nberktumer** [comment]
I think this host configuration is correct, but it seems you are getting "unknown service" error. Have you installed the [HA Integration](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection?tab=readme-ov-file#2-install-home-assistant-integration) in step 2 (Not the blueprint or docker container)?

**Comment by SebastianOlthuis** [comment]
yes i can redo it real quick by removing blueprint&conftainer real quick

**Comment by nberktumer** [comment]
Can you check whether the following entities are available in your system:
<img width="1228" alt="image" src="https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/23507867/a485cd6f-65bc-49d0-b3dc-6f9c8ae2b438">

Also the predict service:
<img width="1350" alt="image" src="https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/23507867/51dfa1ee-2f55-48c7-8cc9-4f30e7bbe8a1">

**Comment by SebastianOlthuis** [comment]
they where not i checked as soon i saw the service error for the first time.

But i have great news the complete redoing it worked for some reason probalby my mistake. 
![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/127320678/4bdcac66-98df-4a73-866f-5dd2199215ee)

also see the service now (it should stay empty i assume)
