### ISSUE TITLE
Question about some blueprint settings.

### ISSUE THREAD

**Issue by hmjgriffon1** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#24]
In the automation settings under Home Assistant Host, I have a public DNS name that points to my home assistant on port 443 and an internal dns record that points to the internal IP, should this work?

Also for Obico ML API Host same as above, I used the public DNS name that resolves to the internal IP of my home assistant when inside the LAN, and specified port 3333, should this also work?

**Comment by nberktumer** [comment]
Yes, it should work as long as your internal DNS record is accessible within your Home Assistant host. 

The automation sends a [GET request](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/blob/932bc67c4ddca86b97b261183f30c18e5fab3f60/custom_components/bambu_lab_p1_spaghetti_detection/__init__.py#L37C1-L38C1) to the specified "Obico ML API Host" parameter. If you can access to your internal DNS record in the HA host, it will work.

**Comment by hmjgriffon1** [comment]
thank you sir.
