### ISSUE TITLE
Errors: Actions not found

### ISSUE THREAD

**Issue by matthawley** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#27]
I'm not positive if this is related to updating to the latest version (v1.1.0) while also running a print. But I'm receiving the following errors:

- The automation "[BAMBU] - Spaghetti Detection" (automation.bambu_spaghetti_detection) has an unknown action: number.set_value.
- The automation "[BAMBU] - Spaghetti Detection" (automation.bambu_spaghetti_detection) has an unknown action: bambu_lab_p1_spaghetti_detection.predict.

Let me know if there are any more details you'd like. I'll re-test after my print is completed (~5hr) to see if it was something due to updating in the middle.

**Comment by nberktumer** [comment]
Could you go to automation > traces > Choose a trace time with seconds is multiples of 5 (e.g. November 4, 2024 at 8:40:10 PM, not 8:41:11 PM) > select the failing node in the trace and send a screentshot of if?

**Comment by matthawley** [comment]
Actually, I think I sorted it out - I had cleaned things up (was using the pull request fork) and forgot to re-add the HACS integration.

**Comment by matthawley** [comment]
Equivalent to issue #21
