### ISSUE TITLE
Installation for current release blueprint should call out Home Assistant compatibility

### ISSUE THREAD

**Issue by pengee** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#29]
Apologies if this is an incorrect location.

It should be called out in the instructions that the current blueprint makes use of 'Triggers', 'Actions' and 'Conditions' in the YAML syntax which was only introduced in Home Assistant 2024.10. For older installations of HA, an automation derived from current blueprint with time trigger will fail to save.

**Comment by nberktumer** [comment]
Thank you for reporting the issue. Yes, you are right, the old syntax would have been used for backward compatibility. I published a new release v1.1.1 for fixing the compatibility.
