### ISSUE TITLE
Camera Entity Not Showing in Blueprint

### ISSUE THREAD

**Issue by Fredy-1** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#30]
Hello!
The image entity has now been changed to a camera entity. 
However, in the Bambu Lab P1 - Spaghetti Detection 1.0.0 blueprint, when specifying the "Printer Camera Imega Entity," the new camera entity does not appear as an option—only the older image entities are available. 
The latest Bambu Lab Home Assistant integration (version 2.0.33) now only supports camera entities, so this setup isn’t working correctly with the P1S printer.

![Képernyőfelvétel (763)](https://github.com/user-attachments/assets/2f0c60fa-bcdb-4756-b4e0-e63f8d16a75a)
![cam](https://github.com/user-attachments/assets/caf52f07-a511-4f90-8095-d638a89929ef)

**Comment by nberktumer** [comment]
Can you try re-importing the blueprint? 

Go to settings > Automations & scenes > blueprints > Click ⋮ icon at the end of the blueprint > Re-import blueprint.

**Comment by Fredy-1** [comment]
> Can you try re-importing the blueprint?
> 
> Go to settings > Automations & scenes > blueprints > Click ⋮ icon at the end of the blueprint > Re-import blueprint.

That's the solution, Thank you!
