### ISSUE TITLE
Blueprint won't save (Message malformed error)

### ISSUE THREAD

**Issue by Captain0Kangaroo** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#35]
On saving the blueprint i'm getting this error and cant save it:

Message malformed: required key not provided @ data['trigger'][4]['platform']

Any ideas?

**Comment by BlueNickDev** [comment]
Here is the problem
![image](https://github.com/user-attachments/assets/8771a45b-28c9-4405-be96-537d30520b9b)
Open the editor in YAML and change it.

I'm not 100% sure because I'm not familiar with blueprints in HA; I've only followed the error displayed...

@nberktumer do you confirm that is the problem? Thanks!

**Comment by Captain0Kangaroo** [comment]
My YAML doesn't look like yours for some reason.
<img width="742" alt="image" src="https://github.com/user-attachments/assets/aef289e5-e32d-42b7-8422-4662b2a1bb8c" />

**Comment by Captain0Kangaroo** [comment]
My YAML doesn't look the same as yours?
<img width="742" alt="image" src="https://github.com/user-attachments/assets/7facc164-fb4f-4de3-9e9a-fcfe8039e05f" />

**Comment by BlueNickDev** [comment]
No, you need to populate all the fields, then click on take control
![image](https://github.com/user-attachments/assets/367843c8-a6f7-4144-8cf3-6d9ce9851afd)
then again on the menu "edit as yaml"

**Comment by nberktumer** [comment]
That seems to be the problem and `platform: time_pattern` line shouldn't be there in the latest version. Could you try re-importing the blueprint by going to `Settings > Automations & Scenes > Blueprints > Click 3 dot icon at the right > Re-import blueprint`?

**Comment by BlueNickDev** [comment]
After reimporting and creating the automation this is the result.
![image](https://github.com/user-attachments/assets/33393e96-3dd0-4196-a584-2eef20fc7d13)
and seems working now for me.
