### ISSUE TITLE
Service bambu_lab_p1_spaghetti_detection.predict not found

### ISSUE THREAD

**Issue by qwasy** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#4]
I tried your detection, and I always get the following two errors:

2024-02-10 12:08:58.950 ERROR (MainThread) [homeassistant.components.automation.bambu_lab_p1_spaghetti_detection] Bambu Lab P1 - Spaghetti Detection: Choose at step 1: choice 3: Error executing script. Service not found for call_service at pos 3: Service bambu_lab_p1_spaghetti_detection.predict not found.

2024-02-10 12:08:58.953 ERROR (MainThread) [homeassistant.components.automation.bambu_lab_p1_spaghetti_detection] Bambu Lab P1 - Spaghetti Detection: Error executing script. Service not found for choose at pos 1: Service bambu_lab_p1_spaghetti_detection.predict not found.

I installed Obico as a HA Addon, and it starts fine.

My blueprint looks like this:

alias: Bambu Lab P1 - Spaghetti Detection
description: ""
use_blueprint:
  path: nberktumer/spaghetti_detection.yaml
  input:
    home_assistant_host: http://192.168.1.4:8123
    obico_host: http://192.168.1.4:3333
    auto_turn_on_light: false
    printer_print_status_sensor: sensor.p1p_xxx_print_status
    printer_current_stage_sensor: sensor.p1p_xxx_current_stage
    printer_camera_image: image.p1p_xxx_camera
    printer_pause_button: button.p1p_xxx_pause_printing
    printer_resume_button: button.p1p_xxx_resume_printing
    printer_stop_button: button.p1p_xxx_stop_printing
    printer_chamber_light: light.p1p_xxx_chamber_light

I use the Obico addon with defaul settings, api_secret and port is the default one.
Here are the logs from the addon:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ha-bambulab-spaghetti-detection (no readiness notification)
s6-rc: info: service legacy-services successfully started
[2024-02-10 12:05:59 +0100] [98] [INFO] Starting gunicorn 19.9.0
[2024-02-10 12:05:59 +0100] [98] [INFO] Listening at: http://0.0.0.0:3333 (98)
[2024-02-10 12:05:59 +0100] [98] [INFO] Using worker: sync
<frozen os>:1031: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
[2024-02-10 12:05:59 +0100] [99] [INFO] Booting worker with pid: 99
   layer   filters  size/strd(dil)      input                output
   0 conv     32       3 x 3/ 1    416 x 416 x   3 ->  416 x 416 x  32 0.299 BF
   1 max                2x 2/ 2    416 x 416 x  32 ->  208 x 208 x  32 0.006 BF
   2 conv     64       3 x 3/ 1    208 x 208 x  32 ->  208 x 208 x  64 1.595 BF
   3 max                2x 2/ 2    208 x 208 x  64 ->  104 x 104 x  64 0.003 BF
   4 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
   5 conv     64       1 x 1/ 1    104 x 104 x 128 ->  104 x 104 x  64 0.177 BF
   6 conv    128       3 x 3/ 1    104 x 104 x  64 ->  104 x 104 x 128 1.595 BF
   7 max                2x 2/ 2    104 x 104 x 128 ->   52 x  52 x 128 0.001 BF
   8 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
   9 conv    128       1 x 1/ 1     52 x  52 x 256 ->   52 x  52 x 128 0.177 BF
  10 conv    256       3 x 3/ 1     52 x  52 x 128 ->   52 x  52 x 256 1.595 BF
  11 max                2x 2/ 2     52 x  52 x 256 ->   26 x  26 x 256 0.001 BF
  12 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  13 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  14 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  15 conv    256       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x 256 0.177 BF
  16 conv    512       3 x 3/ 1     26 x  26 x 256 ->   26 x  26 x 512 1.595 BF
  17 max                2x 2/ 2     26 x  26 x 512 ->   13 x  13 x 512 0.000 BF
  18 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  19 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  20 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  21 conv    512       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x 512 0.177 BF
  22 conv   1024       3 x 3/ 1     13 x  13 x 512 ->   13 x  13 x1024 1.595 BF
  23 conv   1024       3 x 3/ 1     13 x  13 x1024 ->   13 x  13 x1024 3.190 BF
  24 conv   1024       3 x 3/ 1     13 x  13 x1024 ->   13 x  13 x1024 3.190 BF
  25 route  16 		                           ->   26 x  26 x 512 
  26 conv     64       1 x 1/ 1     26 x  26 x 512 ->   26 x  26 x  64 0.044 BF
  27 reorg                    / 2   26 x  26 x  64 ->   13 x  13 x 256
  28 route  27 24 	                           ->   13 x  13 x1280 
  29 conv   1024       3 x 3/ 1     13 x  13 x1280 ->   13 x  13 x1024 3.987 BF
 Try to load cfg: /app/model/model.cfg, weights: /app/lib/../model/model-weights.darknet, clear = 0 
mini_batch = 1, batch = 8, time_steps = 1, train = 0 
 Try to load weights: /app/lib/../model/model-weights.darknet 
  30 conv     30       1 x 1/ 1     13 x  13 x1024 ->   13 x  13 x  30 0.010 BF
  31 detection
mask_scale: Using default '1.000000'
Total BFLOPS 29.338 
avg_outputs = 607364 
Loading weights from /app/lib/../model/model-weights.darknet...Done! Loaded 32 layers from weights-file 

What am I missing?

**Comment by iNaiks** [comment]
Same for me

**Comment by nberktumer** [comment]
Have you installed the "Bambu Lab P1 - Spaghetti Detection" integration? If so, can you share the entities of the integration like this:
![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/23507867/a98d2876-3a64-4a5f-a416-8721e6a5d892)

**Comment by iNaiks** [comment]
Hahahaha, no, sorry, only added the integration on HACS. 😂 Now I will try. Very thanks

**Comment by vordenken** [comment]
I installed the integration but have the same error. Newest HomeAssistant version.
