### ISSUE TITLE
Use this integration with default Obico installation?

### ISSUE THREAD

**Issue by N1c093** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#5]
Hello,

is it possible to use this integration with the default Obico installation? See this guide: https://www.obico.io/docs/server-guides/install/
I can't see an option to create/set the required api key.

What is the difference between the official docker installation from Obico and your docker container?

Thank you

**Comment by ForceConstant** [comment]
@N1c093 did you get this working?

**Comment by N1c093** [comment]
@ForceConstant 
Sadly not. I setup my Obico instance on Oracle Cloud with this guide: https://github.com/MallocArray/obico-oraclecloud
As I'm not familiar with Oracle Cloud, I don't know how I can add the required environment variable.

**Comment by ForceConstant** [comment]
So wanted to let you know that this is working fine using the standard installation of obico in docker. Specifically this project only uses the ML service, and doesn't communicated with the web/task so you can leave that out. Here is my docker-compose.

services:
  redis:
    restart: unless-stopped
    image: redis:7.2-alpine
  ml_api:
    restart: unless-stopped
    image: ghcr.io/thespaghettidetective/obico-server/ml:0.1.0-release.1.4241
    environment:
      - REDIS_URL=redis://redis:6379
      - ML_API_TOKEN=obico_api_secret
      - TZ=America/New_York
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    ports:
      - 3333:3333
    command: bash -c "gunicorn --bind 0.0.0.0:3333 --workers 1 wsgi"

**Comment by fryc88** [comment]
> obico_api_secret

So did you  managed to get normal Obico working along with this Bambu addon using just one installation, or you have only used ML image from official release with it?
