### ISSUE TITLE
New install, how to tell if it is working?

### ISSUE THREAD

**Issue by ForceConstant** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#6]
So I installed obico using the docker-compose method listed, and if I go to <host>:3333 I get a 404, is this expected? If this expected, how do I tell if things are working?

**Comment by nberktumer** [comment]
Yes, it is expected. You can try accessing to `<host>:3333/hc/`, it should print "ok". If so, you can try throwing some print poop to the bed during a print and check the EWM mean value from HA. If the automation detects any failure, the EWM mean value will be greater than 0.

**Comment by ForceConstant** [comment]
I had the obico host still as default. So fixed that now, and it is working. Thanks.
