### ISSUE TITLE
Automation call unknown service

### ISSUE THREAD

**Issue by Just-Toast** [nberktumer/ha-bambu-lab-p1-spaghetti-detection#9]
Hi,

I was trying to install the spaghetti detection, now the moment i start an print on my Bambulab i get the following error.

![image](https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/assets/95021175/65a1194b-0d63-4a84-a518-53de3a5294f9)

Do you guys have any idea how I can solve this problem?

**Comment by nberktumer** [comment]
Have you installed the Spaghetti Detection integration?

> Go to Settings → Devices & services → Add Integration and add Bambu Lab P1 - Spaghetti Detection integration.
